### ISSUE TITLE
[Issue] user redeemed tokens but cant see them in his balance

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2782] opened 2023-01-06 06:17 UTC
**Describe the issue**
user redeemed operator rewards neither appear in balance nor in "unlocked transferable tokens" he did 2 times a claim but the gym tokens seems gone.

**Expected behaviour**
the tokens should appear either in balance or in unlocked transferable tokens"

**Steps to Reproduce**
press claim on operator rewards

**Screenshots**
no

**Which area of Nym were you using?**
node runs on unnix wallet on macOS

**Additional context**
wallet addy: 
n1depxyx74f2nqeld0evre0jgcgtuxlx8lfmt4ee
operator: diamondhand

claim txs:
https://nym.explorers.guru/transaction/6CC985E6039E05FA97E7E4CB3A3861E18BDB54A37F4811E6CC08D2B0683E4B1E
https://nym.explorers.guru/transaction/100ADDDA1D4B4D34FBB27411C4796CF6B8E3D915F5F84F417083A1426429E334

when claimed I think the wallet was on 1.1.3 I updated now to 1.1.5 but that did not change anything. we always updated the node when needed.. so now its on 1.1.4 (I think today will be next update)

thank u for ur help

**Comment by roomit-xyz** [comment] 2023-01-27 20:36
Hallo,

This same case with me, please find :
https://nym.explorers.guru/transaction/1A819AE557760F4864DC4F7545BC78B1887D0AA39DAA606A58F0366E15D7F75A
https://nym.explorers.guru/transaction/1A819AE557760F4864DC4F7545BC78B1887D0AA39DAA606A58F0366E15D7F75A
https://nym.explorers.guru/transaction/8C4DE00ABBCC10B8262E2A9C0C0889DBF0F024D5FC6CBCF7A7A35F7510E246E9

I have redeemed but reward not shown in my main wallet.


Best Regards
Dwi

**Comment by tommyv1987** [comment] 2023-01-31 14:50
Hi all,

Sorry for the delay in getting back to you, we know this is important, and we're investigating the issue now.

@roomit-xyz can you tell me if you were using the SDK to redeem  you rewards, as the memo field look different to wallet usage?

and i'm also looking into the first issue mentioned too.

**Comment by roomit-xyz** [comment] 2023-02-01 00:58
I use new wallet 1.1.8.

actually, the issue claim commision reward not show or not recieve in main wallet balance available since use wallet 1.1.5.

everytime I claimed, not transferred to main wallet. 

Is my fund reward commision safe? I lose many NYM anyway!

**Comment by roomit-xyz** [comment] 2023-02-03 04:06
Hows progress? is my fund reward commision lose?

**Comment by tommyv1987** [comment] 2023-02-03 07:15
@roomit-xyz - we're still looking into the issue, your rewards aren't lost everything is tracked on chain. Have you delegated to your own mixnode? And are you withdrawing your own rewards from your own mixnode? Are you also using vesting tokens to do your delegations?

**Comment by roomit-xyz** [comment] 2023-02-18 05:25
I claim/redeem reward operator, but still not show in wallet available balance. please check asap! https://nym.explorers.guru/transaction/D0FA2374A50CABEB28A1CAC724FA7E3490C32AFE53EDC1233695C187E72750AF

**Comment by tommyv1987** [comment] 2023-02-20 07:59
Hi all, 

We've identified were the problem is stemming from, and no tokens are lost. We intend to release something to address this shortly.

I will update this ticket accordingly and notify you all once it's deployed.

Thanks
Tommy

**Closed as completed** 2023-03-01 12:04 UTC
Labels: bug, mixnode
