### ISSUE TITLE
[Issue] Reduce BOND 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#3667] opened 2023-07-12 08:32 UTC
**Describe the issue**
Users face with the problem that I will share the screenshots below while using the 'Reduce BOND' feature.

**Screenshots**

These are the 4 screenshots of the same wallet. When the user wants to reduce the bond amount to 1500, everything is fine, but when he wants to reduce it to 1000, he faces with the error in the 4th screenshot.

https://paste.pics/ORJRD
https://paste.pics/ORJRI
https://paste.pics/ORJRO
https://paste.pics/ORJRS

**Which area of Nym were you using?**

Nym Wallet v1.2.5

**Comment by benedettadavico** [comment] 2023-07-13 15:06
hey @merve64 this issue is a duplicate of https://github.com/nymtech/nym/issues/3630, it has now been picked up by the devs to work on. Going to close this issue in favour of the other one

**Closed as completed by benedettadavico** 2023-07-13 15:06 UTC
Labels: bug
