### ISSUE TITLE
Error while attempting to reduce the bond amount using Nym Wallet

### ISSUE THREAD

**Issue by lhadri** [nymtech/nym#3630] opened 2023-06-30 16:18 UTC
**Describe the issue**
Reducing the bond amount using the 'Change bond amount' feature in Nym Wallet fails.

**Expected behaviour**
I was expecting to have 5209 bounded NYM after reducing the initially bounded amount of 10418 NYM to half.

**Stack Traces**
Abci query failed with code 6 - rpc error: code = Unknown desc = failed to execute message; message index: 0: 457004116unym is smaller than 5209000000unym: insufficient funds [cosmos/cosmos-sdk@v0.45.14/x/bank/keeper/send.go:186] With gas wanted: '0' and gas used: '112368' : unknown request

**Steps to Reproduce**
- Given I was bonding 10418 NYM
- And I funded my account with 457 NYM (my balance)
- When I reduced the bonded amount to half by typing 5209 in the 'New bond amount' field
- Then I was presented with an error

**Screenshots**
![nym_wallet_bug](https://github.com/nymtech/nym/assets/98365596/1fc9b242-48b4-463c-b014-e5a594fb6bb4)

**Which area of Nym were you using?**
 - Application: Nym Wallet
 - Nym Wallet Version: 1.2.4
 - OS: Windows 11

**Comment by doums** [comment] 2023-07-13 15:54
After checking the code, the issue seems located in the smart contract?
The wallet calls this to simulate the fees cost for the op:
https://github.com/nymtech/nym/blob/6d79b6f6005dbc9c5d339aeb3ca08bcd12cb1624/nym-wallet/src-tauri/src/operations/simulate/mixnet.rs#L125

@jstuczyn @octol 

For context @benedettadavico reproduced the issue and identified the faulty case:
> I managed to reproduce it and the issue seems to be that when reducing the bond amount, the wallet is checking whether the user has enough to cover the difference of the original bond - the new bond.
Example (seen in video below):
original bond - new bond = difference
119 - 108 = 11 ---> reduce bond works
119 - 107 = 12 ---> reduce bond fails
So if the difference > the user's NYM balance, they will get this error

So either the input values we pass to `ExecuteMsg::DecreasePledge` from the wallet is wrong (but I doubt about that since it works for other wallet balance and pledge amount). Or the issue is located in the contract method that handles `DecreasePledge` operation

**Comment by tommyv1987** [comment] 2023-07-18 14:55
A new wallet release is due to go out today and this functionality has now been tested. Closing the ticket

**Closed as completed by tommyv1987** 2023-07-18 14:55 UTC
Labels: bug, qa
