### ISSUE TITLE
[Issue] Main website -» wallet download (https://nymtech.net/download-nym-wallet/) upper tab on safari says: NYM I translation missing: en.page.download...

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2155] opened 2022-12-04 07:21 UTC
**Describe the issue**
Main website -» wallet download (https://nymtech.net/download-nym-wallet/) upper tab on safari says: NYM I translation missing: en.page.download...

**Expected behaviour**
the tab not to say this - looks amateur.

**Steps to Reproduce**
clicking on the dowload wallet button on main site

**Screenshots**
https://imgur.com/a/rEZEZUC

**Which area of Nym were you using?**
safari Version 15.6.1 (17613.3.9.1.16)
macOS monterey 12.6.1

**Comment by tommyv1987** [comment] 2023-02-02 07:23
Cannot reproduce this issue, nor see where the problems stems from here. Closing the issue. In the future, if we can get screenshots with these, that would help too.

**Closed as completed by tommyv1987** 2023-02-02 07:23 UTC
Labels: bug
