### ISSUE TITLE
[Issue] App crash while opening

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2153] opened 2022-12-04 07:32 UTC
**Describe the issue**
App crash while opening

**Expected behaviour**
not crash 

**Steps to Reproduce**
open wallet and works

**Screenshots**
https://drive.google.com/file/d/1OA9f0EWTwp8KZoeV2LPStuj3SmggnE-a/view

**Which area of Nym were you using?**
https://drive.google.com/file/d/16sk_YhE4J36D1t8snNeY_ECh0WFubdAc/view

**Comment by tommyv1987** [comment] 2023-02-02 07:21
A lot more wallet iterations have been released since this issue, and I'm unable to reproduce this issue now. Closing on the preface that the issue is fixed in later versions.

**Closed as completed by tommyv1987** 2023-02-02 07:21 UTC
Labels: bug
