### ISSUE TITLE
[Issue] The wallet stopped working, after a Windows update.

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#4238] opened 2023-12-11 15:24 UTC
**Describe the issue**
The user is unable to open the Nym wallet.

**Expected behaviour**

1. Download and install the Nym wallet software.
2. Open the wallet application.
3. EInput the correct mnemonic when prompted.
4. Attempt to log in..

**Steps to Reproduce**
1. He downloaded and installed the Nym wallet software.
2. After installation, he attempted to open the wallet application by clicking on the icon.
3. No error messages were displayed, but the wallet did not open as expected.

**Screenshots**
https://matrix.to/#/!roIhWTgMVzjBNpTliw:nymtech.chat/$TR01TdzAvU5KjqOJprUUWc-J02lo2Pns_Vw5Z50FXr4?via=nymtech.chat&via=matrix.org&via=mandragot.org

**Which area of Nym were you using?**
Windows 11, RAM 16gb, nvme 500gb, gtx1060 3gb, ryzen 5 4500.

**Comment by tommyv1987** [comment] 2024-01-04 14:49
I cannot reproduce this issue, is the user still experiencing this?

**Comment by merve64** [comment] 2024-02-12 13:28
Yes. When user opens NymWallet, it suddenly closes automatically.

How to reproduce these steps
Open NymWallet

What was the behaviour you expected?
When user opens NymWallet, it doesn't close or exit without action from his side.

Screenshots
n/a

Hardware specs on your device
I use latest version of NymWallet (1.2.11) and Windows 10 Pro.

**Comment by tommyv1987** [comment] 2024-02-15 12:20
We have a new wallet version inbound, let's try and get the user to run this. Version 1.2.12 will be released today. I can not reproduce this error. And make sure the user isn't connected to any proxy / vpn whilst trying.

And the wallet works fine on windows 10 pro. Closing with the ability to re-open if the user experiences any issues.

**Closed as completed by tommyv1987** 2024-02-15 12:20 UTC
Labels: bug, wallet
